"""
Django settings for econometric project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mn104=x*b*_ur8al283&(4^f8imuv_@gfy@@-2k63g1r7lkr=7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# STATIC_ROOT = os.path.join(BASE_DIR, "static")

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'corsheaders',
    'app.apps.AppConfig',
    'forecast.apps.ForcastConfig',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)

ROOT_URLCONF = 'econometric.urls'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, 'templates'),
    os.path.join(BASE_DIR, 'model'),
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'econometric.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'econometric',
        'USER': 'root',
        "PASSWORD": '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'app.User'
AUTHENTICATION_BACKENDS = [
    'app.backend.AppAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ALGORITHM_ROOT = os.path.join(BASE_DIR, 'app', 'algorithm')

DATA_ROOT = os.path.join(BASE_DIR, 'static', 'dataset')

MODEL_ROOT = os.path.join(BASE_DIR, 'static', 'model')

IMG_ROOT = os.path.join(BASE_DIR, 'static', 'images')

TEMPLATE_ROOT = os.path.join(BASE_DIR, 'templates')

SIMPLEUI_HOME_INFO = False

SIMPLEUI_CONFIG = {
    'menus': [
        {
            'name': '首页管理',
            'icon': 'far fa-file-alt',
            'models': [
                {
                    'name': "图片管理",
                    'icon': "fas fa-images",
                    'url': 'app/index_img'
                },
                {
                    'name': "文字管理",
                    'icon': "fas fa-font",
                    'url': 'app/index_text'
                }
            ]
        },
        {
            'name': '服务对象页面管理',
            'icon': 'far fa-file-alt',
            'models': [
                {
                    'name': "图片管理",
                    'icon': "fas fa-images",
                    'url': 'app/serviceobject_img'
                },
                {
                    'name': "文字管理",
                    'icon': "fas fa-font",
                    'url': 'app/serviceobject_text'
                }
            ]
        },
        {
            'name': '解决方案页面管理',
            'icon': 'far fa-file-alt',
            'models': [
                {
                    'name': "图片管理",
                    'icon': "fas fa-images",
                    'url': 'app/solution_img'
                },
                {
                    'name': "文字管理",
                    'icon': "fas fa-font",
                    'url': 'app/solution_text'
                }
            ]
        },
        {
            'name': '账户管理',
            'icon': 'fas fa-address-book',
            'models': [
                {
                    'name': '账户',
                    'icon': "fas fa-user",
                    'url': 'app/user'
                }
            ]
        },
        {
            'name': '算法管理',
            'icon': 'fas fa-calculator',
            'models': [
                {
                    'name': '算法',
                    'icon': 'fas fa-calculator',
                    'url': 'app/algorithm'
                },
                {
                    'name': '参数',
                    'icon': 'fas fa-calculator',
                    'url': 'app/parameter'
                }
            ]
        },
        {
            'name': "预测管理",
            'icon': 'fas fa-folder',
            'models': [
                {
                    'name': '预测实例',
                    'icon': 'fas fa-database',
                    'url': 'app/forecast'
                },
                {
                    'name': '数据',
                    'icon': 'fas fa-table',
                    'url': 'app/dataset'
                }
            ]
        },
        {
            'name': '财务管理',
            'icon': 'fas fa-coins',
            'models': [
                {
                    'name': '余额',
                    'icon': 'fas fa-credit-card',
                    'url': 'app/balance',
                },
                {
                    'name': '订单历史',
                    'icon': 'fas fa-clipboard',
                    'url': 'app/orderhistory',
                }
            ]
        }
    ]
}
